name: Channel

on: workflow_dispatch

jobs:
  channel:
    name: Release Channel
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Channel Version
        uses: sergeysova/jq-action@v2
        id: channel
        with:
          cmd: jq -c '.version | capture("(?<major>[0-9]+)\\.(?<minor>[0-9]+)\\.(?<dot>[0-9]+)")' package.json
      - name: Major version
        uses: sergeysova/jq-action@v2
        id: major
        with:
          cmd: echo '${{ steps.channel.outputs.value }}' | jq .major
      - name: Minor version
        uses: sergeysova/jq-action@v2
        id: minor
        with:
          cmd: echo '"${{ steps.channel.outputs.value }}' | jq .minor
      - name: Dot version
        uses: sergeysova/jq-action@v2
        id: dot
        with:
          cmd: echo '${{ steps.channel.outputs.value }}' | jq .dot
      - name: Show Channel Version
        run: 'echo "channel ${{ steps.major.outputs.value }}.${{ steps.minor.outputs.value }}.${{ steps.dot.outputs.value }}"'
